#!/usr/bin/env python3
"""Generate C shims for every external `ame_mm_*` function that appears in the
LLVM-dialect MLIR. Also verifies the expanded-descriptor ABI assumption:
each such function must take exactly 21 arguments (3 rank-2 memrefs x 7)."""
import re
import sys

EXPECTED_ARGS = 21


def main(mlir_path, out_path):
    text = open(mlir_path).read()
    found = re.findall(r"llvm\.func\s+(?:\w+\s+)*@(ame_b?mm_[A-Za-z0-9_]+)\(([^)]*)\)", text)
    if not found:
        sys.exit(f"gen_shims: no ame_mm_* declarations found in {mlir_path}")
    lines = [
        "/* AUTO-GENERATED by mlir/gen_shims.py -- do not edit */",
        '#include "memref_shims.h"',
        "",
    ]
    seen = set()
    for name, params in found:
        if name in seen:
            continue
        seen.add(name)
        nargs = len([p for p in params.split(",") if p.strip()])
        want = 27 if name.startswith("ame_bmm_") else EXPECTED_ARGS
        if nargs != want:
            sys.exit(
                f"gen_shims: @{name} has {nargs} args, expected {want}. "
                "The memref calling convention differs from the assumption; "
                "paste the declaration to Claude."
            )
        if name.startswith("ame_bmm_f32_"):
            lines.append(f"AME_SHIM3({name}, ame_bmm_f32_memref)")
            continue
        if name.startswith("ame_mm_f32_"):
            impl = "ame_matmul_f32_memref"
        elif name.startswith("ame_mm_i8_"):
            impl = "ame_matmul_i8_memref"
        else:
            sys.exit(f"gen_shims: no implementation for {name}")
        lines.append(f"AME_SHIM({name}, {impl})")
    open(out_path, "w").write("\n".join(lines) + "\n")
    print(f"generated {len(seen)} shim(s) -> {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: gen_shims.py lowered.mlir out.c")
    main(sys.argv[1], sys.argv[2])
