#!/usr/bin/env python3
"""Generate a bare-metal driver for a model `forward(in) -> out` (single f32 input, single f32 output, any rank<=6).
usage: gen_driver.py model.json out.c [RUNS=2]      (model.json: {"in_shape":[..], "out_shape":[..]})
The driver prints SAMP lines (evenly spaced output elements as raw bits), OUTN, SUMSQ and STATS; python/compare_tensor.py checks them."""
import json, sys
meta = json.load(open(sys.argv[1]))
runs = int(sys.argv[3]) if len(sys.argv) > 3 else 2   # 1 = single cold run (for very large models)
ins, outs = meta["in_shape"], meta["out_shape"]
def prod(v):
    r = 1
    for a in v: r *= a
    return r
def strides(v):
    s, r = [], 1
    for a in reversed(v): s.append(r); r *= a
    return list(reversed(s))
def arr(v): return "{" + ", ".join(str(a) for a in v) + "}"
src = f'''/* AUTO-GENERATED by python/gen_driver.py -- do not edit. in {ins} -> out {outs} */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "ame_kernel.h"
#define N_IN  {prod(ins)}
#define N_OUT {prod(outs)}
typedef struct {{ float *alloc, *align; int64_t off, sizes[{len(ins)}]; int64_t strides[{len(ins)}]; }} MemRefIn;
typedef struct {{ float *alloc, *align; int64_t off, sizes[{len(outs)}]; int64_t strides[{len(outs)}]; }} MemRefOut;
extern void _mlir_ciface_forward(MemRefOut *out, MemRefIn *in);
extern const unsigned char _binary_input_bin_start[];
static float g_in[N_IN] __attribute__((aligned(64)));
static float g_out[N_OUT] __attribute__((aligned(64)));
int main(void) {{
  memcpy(g_in, _binary_input_bin_start, sizeof(g_in));
  MemRefIn in = {{g_in, g_in, 0, {arr(ins)}, {arr(strides(ins))}}};
  MemRefOut out = {{g_out, g_out, 0, {arr(outs)}, {arr(strides(outs))}}};
  extern unsigned long ame_instret_in_matmul, ame_ksteps, ame_otiles, ame_instret_in_copy, ame_copy_calls;
  for (int run = 0; run < {runs}; run++) {{
    ame_stats_reset();
    ame_instret_in_matmul = ame_ksteps = ame_otiles = ame_instret_in_copy = ame_copy_calls = 0;
    unsigned long ir0, ir1;
    __asm__ volatile("rdinstret %0" : "=r"(ir0));
    _mlir_ciface_forward(&out, &in);
    __asm__ volatile("rdinstret %0" : "=r"(ir1));
    fprintf(stderr, "RUN%d INSTRET forward=%lu in_matmul=%lu in_copy=%lu copy_calls=%lu ksteps=%lu otiles=%lu\\n",
            run, ir1 - ir0, ame_instret_in_matmul, ame_instret_in_copy, ame_copy_calls, ame_ksteps, ame_otiles);
  }}
  const float *o = out.align + out.off;
  const int64_t ns = N_OUT < 2048 ? N_OUT : 2048, step = N_OUT / ns;
  double ss = 0, proj = 0;
  for (int64_t i = 0; i < N_OUT; i++) {{
    ss += (double)o[i] * (double)o[i];
    proj += (double)o[i] * ((double)(int)(((uint32_t)i * 2654435761u) >> 22) - 512.0) / 512.0;  /* fixed pseudo-random weights */
  }}
  for (int64_t s = 0; s < ns; s++) {{
    uint32_t bits; memcpy(&bits, &o[s * step], 4);
    printf("SAMP %ld 0x%08x\\n", (long)(s * step), (unsigned)bits);
  }}
  printf("OUTN %d\\nSUMSQ %.9e\\nPROJ %.9e\\n", N_OUT, ss, proj);
  const ame_stats_t *st = ame_stats_get();
  printf("STATS backend=%s matmul_calls=%lu macs=%lu\\n", ame_backend_name(), (unsigned long)st->calls, (unsigned long)st->macs);
  return 0;
}}
'''
open(sys.argv[2], "w").write(src)
