#!/usr/bin/env python3
"""Generate a bare-metal driver for a model `forward(in) -> out` (single f32 input, single f32 output, any rank<=6).
usage: gen_driver.py model.json out.c [RUNS=2]      (model.json: {"in_shape":[..], "out_shape":[..]})
The driver prints SAMP lines (evenly spaced output elements as raw bits), OUTN, SUMSQ and STATS; python/compare_tensor.py checks them."""
import json, sys
meta = json.load(open(sys.argv[1]))
runs = int(sys.argv[3]) if len(sys.argv) > 3 else 2   # 1 = single cold run (for very large models)
CT = {"float32": "float", "int64": "int64_t"}
if "inputs" in meta:
    ins = meta["inputs"]
else:  # legacy single f32 input
    sh = meta["in_shape"]; n = 1
    for a_ in sh: n *= a_
    ins = [{"shape": sh, "dtype": "float32", "offset": 0, "bytes": 4 * n}]
outs = meta["out_shape"]
W = meta.get("weights")   # weights as arguments: loaded from a file at run time (pk reads host files)
def prod(v):
    r = 1
    for a in v: r *= a
    return r
def strides(v):
    s, r = [], 1
    for a in reversed(v): s.append(r); r *= a
    return list(reversed(s))
def arr(v): return "{" + ", ".join(str(a) for a in v) + "}"
decl, bufs, descs, loads, argl, argd = [], [], [], [], [], []
for k, sp in enumerate(ins):
    t = CT[sp["dtype"]]; sh = sp["shape"]
    decl.append(f"typedef struct {{ {t} *alloc, *align; int64_t off, sizes[{len(sh)}]; int64_t strides[{len(sh)}]; }} MemRefIn{k};")
    bufs.append(f"static {t} g_in{k}[{prod(sh)}] __attribute__((aligned(64)));")
    loads.append(f"  memcpy(g_in{k}, _binary_input_bin_start + {sp['offset']}, {sp['bytes']});")
    descs.append(f"  MemRefIn{k} in{k} = {{g_in{k}, g_in{k}, 0, {arr(sh)}, {arr(strides(sh))}}};")
    argl.append(f"MemRefIn{k} *in{k}"); argd.append(f"&in{k}")
wdecl, wvars, wset = [], [], []
if W:
    ranks = sorted({len(sp["shape"]) for sp in W["specs"]})
    for r in ranks:
        wdecl.append(f"typedef struct {{ float *alloc, *align; int64_t off, sizes[{r}]; int64_t strides[{r}]; }} MRW{r};")
    for k, sp in enumerate(W["specs"]):
        r = len(sp["shape"])
        wvars.append(f"static MRW{r} w{k} = {{0, 0, 0, {arr(sp['shape'])}, {arr(strides(sp['shape']))}}};")
        wset.append(f"  w{k}.alloc = w{k}.align = (float *)(wbase + {sp['offset']});")
        argl.append(f"MRW{r} *w{k}"); argd.append(f"&w{k}")
wload = ""
if W:
    wload = f'''
#include <stdlib.h>
static unsigned char *wbase;
static void load_weights(void) {{
  FILE *f = fopen("{W['file']}", "rb");
  if (!f) {{ printf("cannot open {W['file']} (run spike from the repo root)\\n"); exit(2); }}
  unsigned char *raw = malloc({W['total']} + 64);
  if (!raw) {{ printf("out of memory for weights ({W['total']} bytes): raise SPIKE_MEM\\n"); exit(2); }}
  wbase = (unsigned char *)(((uintptr_t)raw + 63) & ~(uintptr_t)63);
  size_t got = 0;
  while (got < {W['total']}) {{
    size_t n = fread(wbase + got, 1, ({W['total']} - got) < (1u << 22) ? ({W['total']} - got) : (1u << 22), f);
    if (!n) {{ printf("short read of weights at %zu\\n", got); exit(2); }}
    got += n;
  }}
  fclose(f);
}}'''
src = f'''/* AUTO-GENERATED by python/gen_driver.py -- do not edit. {len(ins)} input(s) -> out {outs} */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "ame_kernel.h"
#define N_OUT {prod(outs)}
{chr(10).join(decl)}
{chr(10).join(wdecl)}
{chr(10).join(wvars)}
typedef struct {{ float *alloc, *align; int64_t off, sizes[{len(outs)}]; int64_t strides[{len(outs)}]; }} MemRefOut;
extern void _mlir_ciface_forward(MemRefOut *out, {", ".join(argl)});
extern const unsigned char _binary_input_bin_start[];
{chr(10).join(bufs)}
static float g_out[N_OUT] __attribute__((aligned(64)));
{wload}
int main(void) {{
{chr(10).join(loads)}
{"  load_weights();" if W else ""}
{chr(10).join(wset)}
{chr(10).join(descs)}
  MemRefOut out = {{g_out, g_out, 0, {arr(outs)}, {arr(strides(outs))}}};
  extern unsigned long ame_instret_in_matmul, ame_ksteps, ame_otiles, ame_instret_in_copy, ame_copy_calls;
  for (int run = 0; run < {runs}; run++) {{
    ame_stats_reset();
    ame_instret_in_matmul = ame_ksteps = ame_otiles = ame_instret_in_copy = ame_copy_calls = 0;
    unsigned long ir0, ir1;
    __asm__ volatile("rdinstret %0" : "=r"(ir0));
    _mlir_ciface_forward(&out, {", ".join(argd)});
    __asm__ volatile("rdinstret %0" : "=r"(ir1));
    fprintf(stderr, "RUN%d INSTRET forward=%lu in_matmul=%lu in_copy=%lu copy_calls=%lu ksteps=%lu otiles=%lu\\n",
            run, ir1 - ir0, ame_instret_in_matmul, ame_instret_in_copy, ame_copy_calls, ame_ksteps, ame_otiles);
  }}
  const float *o = out.align + out.off;
  const int64_t ns = N_OUT < 2048 ? N_OUT : 2048, step = N_OUT / ns;
  double ss = 0, proj = 0;
  for (int64_t i = 0; i < N_OUT; i++) {{
    ss += (double)o[i] * (double)o[i];
    proj += (double)o[i] * ((double)(int)(((uint32_t)i * 2654435761u) >> 22) - 512.0) / 512.0;  /* fixed pseudo-random weights */
  }}
  for (int64_t s = 0; s < ns; s++) {{
    uint32_t bits; memcpy(&bits, &o[s * step], 4);
    printf("SAMP %ld 0x%08x\\n", (long)(s * step), (unsigned)bits);
  }}
  printf("OUTN %d\\nSUMSQ %.9e\\nPROJ %.9e\\n", N_OUT, ss, proj);
  const ame_stats_t *st = ame_stats_get();
  printf("STATS backend=%s matmul_calls=%lu macs=%lu\\n", ame_backend_name(), (unsigned long)st->calls, (unsigned long)st->macs);
  return 0;
}}
'''
open(sys.argv[2], "w").write(src)
